# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Out of Bounds: Excetional Technology"
email: info@outofbounds.technology
description: > # this means to ignore newlines until "baseurl:"
  Mobile app marketeers with 15 years combined knowledge and experience. We'll
  help you access the Chinese market, from localisation and marketing to social
  integration and monetisation. We know China's mobile marketplace like no
  other.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://outofbounds.technology" # the base hostname & protocol for your site
twitter_username: marceloomens
github_username:  outofboundstech

# Build settings
markdown: kramdown
